
import __ASTRO_IMAGE_IMPORT_1g3M4C from "@/assets/images/waybar.png?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2F_2026%2F_Enero%2FTI%2Ffedora_hyprland.md";
import __ASTRO_IMAGE_IMPORT_1xEsxs from "@/assets/images/waybarv1.png?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2F_2026%2F_Enero%2FTI%2Ffedora_hyprland.md";
import __ASTRO_IMAGE_IMPORT_ZH1tI6 from "@/assets/images/waybarv3.png?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2F_2026%2F_Enero%2FTI%2Ffedora_hyprland.md";
import __ASTRO_IMAGE_IMPORT_Z2lIOQB from "@/assets/images/rofi.png?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2F_2026%2F_Enero%2FTI%2Ffedora_hyprland.md";
import __ASTRO_IMAGE_IMPORT_Z1fc55X from "@/assets/images/KooL_style-5.png?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2F_2026%2F_Enero%2FTI%2Ffedora_hyprland.md";
import __ASTRO_IMAGE_IMPORT_ZFmPO9 from "@/assets/images/KooL_style-9.png?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2F_2026%2F_Enero%2FTI%2Ffedora_hyprland.md";
import __ASTRO_IMAGE_IMPORT_Z1YiazF from "@/assets/images/Detuned.png?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2F_2026%2F_Enero%2FTI%2Ffedora_hyprland.md";
import __ASTRO_IMAGE_IMPORT_Z1nvnNH from "@/assets/images/Abernathy.png?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2F_2026%2F_Enero%2FTI%2Ffedora_hyprland.md";
import __ASTRO_IMAGE_IMPORT_1w1gSD from "@/assets/images/Black_Metal.png?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2F_2026%2F_Enero%2FTI%2Ffedora_hyprland.md";
import __ASTRO_IMAGE_IMPORT_1GLMR9 from "@/assets/images/Dimidium.png?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2F_2026%2F_Enero%2FTI%2Ffedora_hyprland.md";
import __ASTRO_IMAGE_IMPORT_1BD1Xm from "@/assets/images/nicoulaj.png?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2F_2026%2F_Enero%2FTI%2Ffedora_hyprland.md";
import __ASTRO_IMAGE_IMPORT_Z2lujeh from "@/assets/images/sunrise.png?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2F_2026%2F_Enero%2FTI%2Ffedora_hyprland.md";
import __ASTRO_IMAGE_IMPORT_Zhfq59 from "@/assets/images/Fastfetch.png?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2F_2026%2F_Enero%2FTI%2Ffedora_hyprland.md";
import __ASTRO_IMAGE_IMPORT_ZjjTRi from "@/assets/images/nautilius.png?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2F_2026%2F_Enero%2FTI%2Ffedora_hyprland.md";
import __ASTRO_IMAGE_IMPORT_1FSQdG from "@/assets/images/wal1.png?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2F_2026%2F_Enero%2FTI%2Ffedora_hyprland.md";
import __ASTRO_IMAGE_IMPORT_y3n5p from "@/assets/images/wal2.png?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2F_2026%2F_Enero%2FTI%2Ffedora_hyprland.md";
import __ASTRO_IMAGE_IMPORT_ZyM62R from "@/assets/images/wal3.png?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2F_2026%2F_Enero%2FTI%2Ffedora_hyprland.md";
export default new Map([["@/assets/images/waybar.png?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2F_2026%2F_Enero%2FTI%2Ffedora_hyprland.md", __ASTRO_IMAGE_IMPORT_1g3M4C], ["@/assets/images/waybarv1.png?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2F_2026%2F_Enero%2FTI%2Ffedora_hyprland.md", __ASTRO_IMAGE_IMPORT_1xEsxs], ["@/assets/images/waybarv3.png?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2F_2026%2F_Enero%2FTI%2Ffedora_hyprland.md", __ASTRO_IMAGE_IMPORT_ZH1tI6], ["@/assets/images/rofi.png?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2F_2026%2F_Enero%2FTI%2Ffedora_hyprland.md", __ASTRO_IMAGE_IMPORT_Z2lIOQB], ["@/assets/images/KooL_style-5.png?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2F_2026%2F_Enero%2FTI%2Ffedora_hyprland.md", __ASTRO_IMAGE_IMPORT_Z1fc55X], ["@/assets/images/KooL_style-9.png?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2F_2026%2F_Enero%2FTI%2Ffedora_hyprland.md", __ASTRO_IMAGE_IMPORT_ZFmPO9], ["@/assets/images/Detuned.png?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2F_2026%2F_Enero%2FTI%2Ffedora_hyprland.md", __ASTRO_IMAGE_IMPORT_Z1YiazF], ["@/assets/images/Abernathy.png?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2F_2026%2F_Enero%2FTI%2Ffedora_hyprland.md", __ASTRO_IMAGE_IMPORT_Z1nvnNH], ["@/assets/images/Black_Metal.png?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2F_2026%2F_Enero%2FTI%2Ffedora_hyprland.md", __ASTRO_IMAGE_IMPORT_1w1gSD], ["@/assets/images/Dimidium.png?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2F_2026%2F_Enero%2FTI%2Ffedora_hyprland.md", __ASTRO_IMAGE_IMPORT_1GLMR9], ["@/assets/images/nicoulaj.png?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2F_2026%2F_Enero%2FTI%2Ffedora_hyprland.md", __ASTRO_IMAGE_IMPORT_1BD1Xm], ["@/assets/images/sunrise.png?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2F_2026%2F_Enero%2FTI%2Ffedora_hyprland.md", __ASTRO_IMAGE_IMPORT_Z2lujeh], ["@/assets/images/Fastfetch.png?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2F_2026%2F_Enero%2FTI%2Ffedora_hyprland.md", __ASTRO_IMAGE_IMPORT_Zhfq59], ["@/assets/images/nautilius.png?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2F_2026%2F_Enero%2FTI%2Ffedora_hyprland.md", __ASTRO_IMAGE_IMPORT_ZjjTRi], ["@/assets/images/wal1.png?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2F_2026%2F_Enero%2FTI%2Ffedora_hyprland.md", __ASTRO_IMAGE_IMPORT_1FSQdG], ["@/assets/images/wal2.png?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2F_2026%2F_Enero%2FTI%2Ffedora_hyprland.md", __ASTRO_IMAGE_IMPORT_y3n5p], ["@/assets/images/wal3.png?astroContentImageFlag=&importer=src%2Fdata%2Fblog%2F_2026%2F_Enero%2FTI%2Ffedora_hyprland.md", __ASTRO_IMAGE_IMPORT_ZyM62R]]);
		